/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-16 14:50:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.myclass.constant.UrlConstants;
import com.myclass.entity.NewEntity;
import java.util.List;
import com.myclass.entity.CategoryEntity;

public final class list_002dedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Servlet-Basic/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/tablib.jsp", Long.valueOf(1626012339203L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1625930659352L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1625999286137L));
    _jspx_dependants.put("jar:file:/D:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Servlet-Basic/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.myclass.entity.CategoryEntity");
    _jspx_imports_classes.add("com.myclass.constant.UrlConstants");
    _jspx_imports_classes.add("com.myclass.entity.NewEntity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<CategoryEntity> categories = (List<CategoryEntity>) request.getAttribute("categories");
NewEntity newEntity = (NewEntity) request.getAttribute("news");

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Chỉnh sửa bài viết</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row bg-title\">\r\n");
      out.write("		<div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("			<h4 class=\"page-title\">Edit News</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /.row -->\r\n");
      out.write("	<!-- .row -->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-md-2 col-12\"></div>\r\n");
      out.write("		<div class=\"col-md-8 col-xs-12\">\r\n");
      out.write("			<div class=\"white-box\">\r\n");
      out.write("				<form method=\"post\"\r\n");
      out.write("					action=\"");
      out.print(request.getContextPath() + "/admin/news/list");
      out.write("\"\r\n");
      out.write("					class=\"form-horizontal form-material\">\r\n");
      out.write("					<input type=\"hidden\" name=\"id\" value=\"");
      out.print(newEntity.getId());
      out.write("\"\r\n");
      out.write("						class=\"form-control form-control-line\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label class=\"col-md-12\">Title</label>\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<input value=\"");
      out.print(newEntity.getTitle());
      out.write("\" name=\"title\" type=\"text\"\r\n");
      out.write("								placeholder=\"Title\" class=\"form-control form-control-line\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label class=\"col-md-12\">Short Description</label>\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<input value=\"");
      out.print(newEntity.getShortDescription());
      out.write("\"\r\n");
      out.write("								name=\"Short Description\" type=\"text\" placeholder=\"Description\"\r\n");
      out.write("								class=\"form-control form-control-line\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("						<label class=\"col-md-12\">Content</label>\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<textarea class=\"form-control\" aria-label=\"With textarea\"\r\n");
      out.write("								name=\"content\" value=\"");
      out.print(newEntity.getContent());
      out.write("\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label class=\"col-md-12\">Thumb nail</label>\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<input type=\"file\" name=\"thumbnail\"\r\n");
      out.write("								value=\"");
      out.print(newEntity.getThumbnail());
      out.write("\" class=\"form-control\"\r\n");
      out.write("								id=\"customFile\" />\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label class=\"col-sm-12\">Select Category</label>\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<select name=\"categoryId\" class=\"form-control form-control-line\">\r\n");
      out.write("								");

								for (CategoryEntity categoryEntity : categories) {
									String selected = newEntity.getCategoryId() == categoryEntity.getId() ? "selected" : "";
								
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(categoryEntity.getId());
      out.write('"');
      out.write(' ');
      out.print(selected);
      out.write('>');
      out.print(categoryEntity.getName());
      out.write("</option>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-success\">Update\r\n");
      out.write("								News</button>\r\n");
      out.write("							<a href=\"#\" class=\"btn btn-primary\">Quay lại</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-2 col-12\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
