/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-17 15:54:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.decorators;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/D:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Servlet-Basic/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/admin/menu.jsp", Long.valueOf(1626537260788L));
    _jspx_dependants.put("/common/admin/footer.jsp", Long.valueOf(1626253087516L));
    _jspx_dependants.put("/common/tablib.jsp", Long.valueOf(1626012339203L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1625930659352L));
    _jspx_dependants.put("/common/admin/header.jsp", Long.valueOf(1626267561601L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1625999286137L));
    _jspx_dependants.put("jar:file:/D:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Servlet-Basic/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005fbody_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>");
      if (_jspx_meth_dec_005ftitle_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom link pagination for this template-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<ul\r\n");
      out.write("	class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\r\n");
      out.write("	id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Sidebar - Brand -->\r\n");
      out.write("	<a\r\n");
      out.write("		class=\"sidebar-brand d-flex align-items-center justify-content-center\"\r\n");
      out.write("		href=\"index.html\">\r\n");
      out.write("		<div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("			<i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("			SB Admin <sup>2</sup>\r\n");
      out.write("		</div>\r\n");
      out.write("	</a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Divider -->\r\n");
      out.write("	<hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Nav Item - Dashboard -->\r\n");
      out.write("	<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("			<i class=\"fas fa-fw fa-tachometer-alt\"></i> <span>Dashboard</span>\r\n");
      out.write("	</a></li>\r\n");
      out.write("\r\n");
      out.write("	<!-- Divider -->\r\n");
      out.write("	<hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Heading -->\r\n");
      out.write("	<div class=\"sidebar-heading\">Interface</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("		data-toggle=\"collapse\" data-target=\"#collapseTwo\" aria-expanded=\"true\"\r\n");
      out.write("		aria-controls=\"collapseTwo\"> <i class=\"fas fa-fw fa-cog\"></i> <span>Components</span>\r\n");
      out.write("	</a>\r\n");
      out.write("		<div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\"\r\n");
      out.write("			data-parent=\"#accordionSidebar\">\r\n");
      out.write("			<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("				<h6 class=\"collapse-header\">Custom Components:</h6>\r\n");
      out.write("				<a class=\"collapse-item\"\r\n");
      out.write("					href='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("'>Category</a> <a\r\n");
      out.write("					class=\"collapse-item\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">News</a>\r\n");
      out.write("				<a class=\"collapse-item\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">User</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Divider -->\r\n");
      out.write("	<hr class=\"sidebar-divider\" />\r\n");
      out.write("\r\n");
      out.write("	<!-- Heading -->\r\n");
      out.write("	<div class=\"sidebar-heading\">Addons</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("	<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("		data-toggle=\"collapse\" data-target=\"#collapsePages\"\r\n");
      out.write("		aria-expanded=\"true\" aria-controls=\"collapsePages\"> <i\r\n");
      out.write("			class=\"fas fa-fw fa-folder\"></i> <span>Pages</span>\r\n");
      out.write("	</a>\r\n");
      out.write("		<div id=\"collapsePages\" class=\"collapse\"\r\n");
      out.write("			aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("			<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("				<h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("				<a class=\"collapse-item\" href=\"login.html\">Login</a> <a\r\n");
      out.write("					class=\"collapse-item\" href=\"register.html\">Register</a> <a\r\n");
      out.write("					class=\"collapse-item\" href=\"forgot-password.html\">Forgot\r\n");
      out.write("					Password</a>\r\n");
      out.write("				<div class=\"collapse-divider\"></div>\r\n");
      out.write("				<h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("				<a class=\"collapse-item\" href=\"404.html\">404 Page</a> <a\r\n");
      out.write("					class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<!-- End of Sidebar -->");
      out.write("\r\n");
      out.write("		<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"content\">\r\n");
      out.write("				");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("\r\n");
      out.write("<nav\r\n");
      out.write("	class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("	<button id=\"sidebarToggleTop\"\r\n");
      out.write("		class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("		<i class=\"fa fa-bars\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("\r\n");
      out.write("	<!-- Topbar Search -->\r\n");
      out.write("	<form\r\n");
      out.write("		class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("		<div class=\"input-group\">\r\n");
      out.write("			<input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("				placeholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("				aria-describedby=\"basic-addon2\">\r\n");
      out.write("			<div class=\"input-group-append\">\r\n");
      out.write("				<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("					<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<!-- Topbar Navbar -->\r\n");
      out.write("	<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow d-sm-none\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("			aria-expanded=\"false\"> <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("		</a> <!-- Dropdown - Messages -->\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("				aria-labelledby=\"searchDropdown\">\r\n");
      out.write("				<form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("							placeholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("							aria-describedby=\"basic-addon2\">\r\n");
      out.write("						<div class=\"input-group-append\">\r\n");
      out.write("							<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("								<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div></li>\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav Item - Alerts -->\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("			aria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("				<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("		</a> <!-- Dropdown - Alerts -->\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("				aria-labelledby=\"alertsDropdown\">\r\n");
      out.write("				<h6 class=\"dropdown-header\">Alerts Center</h6>\r\n");
      out.write("				<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"mr-3\">\r\n");
      out.write("						<div class=\"icon-circle bg-primary\">\r\n");
      out.write("							<i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
      out.write("						<span class=\"font-weight-bold\">A new monthly report is\r\n");
      out.write("							ready to download!</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"mr-3\">\r\n");
      out.write("						<div class=\"icon-circle bg-success\">\r\n");
      out.write("							<i class=\"fas fa-donate text-white\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
      out.write("						$290.29 has been deposited into your account!\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"mr-3\">\r\n");
      out.write("						<div class=\"icon-circle bg-warning\">\r\n");
      out.write("							<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
      out.write("						Spending Alert: We've noticed unusually high spending for your\r\n");
      out.write("						account.\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show\r\n");
      out.write("					All Alerts</a>\r\n");
      out.write("			</div></li>\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav Item - Messages -->\r\n");
      out.write("		<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("			class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\"\r\n");
      out.write("			role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("			aria-expanded=\"false\"> <i class=\"fas fa-envelope fa-fw\"></i> <!-- Counter - Messages -->\r\n");
      out.write("				<span class=\"badge badge-danger badge-counter\">7</span>\r\n");
      out.write("		</a> <!-- Dropdown - Messages -->\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("				aria-labelledby=\"messagesDropdown\">\r\n");
      out.write("				<h6 class=\"dropdown-header\">Message Center</h6>\r\n");
      out.write("				<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("						<img class=\"rounded-circle\" src=\"#\"\r\n");
      out.write("							alt=\"...\">\r\n");
      out.write("						<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"font-weight-bold\">\r\n");
      out.write("						<div class=\"text-truncate\">Hi there! I am wondering if you\r\n");
      out.write("							can help me with a problem I've been having.</div>\r\n");
      out.write("						<div class=\"small text-gray-500\">Emily Fowler · 58m</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("						<img class=\"rounded-circle\" src=\"#\"\r\n");
      out.write("							alt=\"...\">\r\n");
      out.write("						<div class=\"status-indicator\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"text-truncate\">I have the photos that you\r\n");
      out.write("							ordered last month, how would you like them sent to you?</div>\r\n");
      out.write("						<div class=\"small text-gray-500\">Jae Chun · 1d</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("						<img class=\"rounded-circle\" src=\"#\"\r\n");
      out.write("							alt=\"...\">\r\n");
      out.write("						<div class=\"status-indicator bg-warning\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"text-truncate\">Last month's report looks great,\r\n");
      out.write("							I am very happy with the progress so far, keep up the good work!</div>\r\n");
      out.write("						<div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("					<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("						<img class=\"rounded-circle\"\r\n");
      out.write("							src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\"\r\n");
      out.write("							alt=\"...\">\r\n");
      out.write("						<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"text-truncate\">Am I a good boy? The reason I ask\r\n");
      out.write("							is because someone told me that people say this to all dogs, even\r\n");
      out.write("							if they aren't good...</div>\r\n");
      out.write("						<div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a> <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read\r\n");
      out.write("					More Messages</a>\r\n");
      out.write("			</div></li>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("<!-- End of Main Content -->");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_dec_005fbody_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("	<div class=\"container my-auto\">\r\n");
      out.write("		<div class=\"copyright text-center my-auto\">\r\n");
      out.write("			<span>Copyright &copy; Your Website 2021</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End of Footer -->");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap core JavaScript-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_dec_005ftitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:title
    com.opensymphony.module.sitemesh.taglib.decorator.TitleTag _jspx_th_dec_005ftitle_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.TitleTag) _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.TitleTag.class);
    boolean _jspx_th_dec_005ftitle_005f0_reused = false;
    try {
      _jspx_th_dec_005ftitle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_dec_005ftitle_005f0.setParent(null);
      // /decorators/admin.jsp(9,7) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_dec_005ftitle_005f0.setDefault("Admin");
      int _jspx_eval_dec_005ftitle_005f0 = _jspx_th_dec_005ftitle_005f0.doStartTag();
      if (_jspx_th_dec_005ftitle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.reuse(_jspx_th_dec_005ftitle_005f0);
      _jspx_th_dec_005ftitle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_dec_005ftitle_005f0, _jsp_getInstanceManager(), _jspx_th_dec_005ftitle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /decorators/admin.jsp(21,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/template/admin/vendor/fontawesome-free/css/all.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /decorators/admin.jsp(28,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/admin/css/sb-admin-2.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /common/admin/menu.jsp(47,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/admin/category/list");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /common/admin/menu.jsp(48,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/admin/news/list");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /common/admin/menu.jsp(49,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/admin/user/list");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_dec_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_dec_005fbody_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    boolean _jspx_th_dec_005fbody_005f0_reused = false;
    try {
      _jspx_th_dec_005fbody_005f0.setPageContext(_jspx_page_context);
      _jspx_th_dec_005fbody_005f0.setParent(null);
      int _jspx_eval_dec_005fbody_005f0 = _jspx_th_dec_005fbody_005f0.doStartTag();
      if (_jspx_th_dec_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.reuse(_jspx_th_dec_005fbody_005f0);
      _jspx_th_dec_005fbody_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_dec_005fbody_005f0, _jsp_getInstanceManager(), _jspx_th_dec_005fbody_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /decorators/admin.jsp(51,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/template/admin/vendor/jquery/jquery.min.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /decorators/admin.jsp(53,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/template/admin/vendor/bootstrap/js/bootstrap.bundle.min.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /decorators/admin.jsp(56,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/template/admin/vendor/jquery-easing/jquery.easing.min.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }
}
